CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    username    VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    role        VARCHAR(16) NOT NULL DEFAULT 'user',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert default admin user (password: admin123)
-- Hash generated by: cargo run --bin hash -- admin123 (bcrypt 0.15)
INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2b$12$VQMPXLLIQ0c2NZCWSEDY9ORDoJGAKGYXQpQHUj8uD2GM2Rv2TK.ye', 'admin')
ON CONFLICT (username) DO NOTHING;
